### ISSUE TITLE
Q: What is TH in the simulations output?

### ISSUE THREAD

**Issue by ulrmu** [sysbio-curie/PROFILE#1]
Hi,
Not an issue, just a question:
In the python simulation script `MaBoSS_specific.py`, a column `TH` is created in the output file. Can anyone explain what `TH` is and how it is used?
Thanks in advance!

**Comment by ArnauMontagud** [comment]
Hi, and thanks to get in touch!
TH stands for Transition Entropy and is a way to measure how deterministic the dynamics is. The full details can be seen [here](https://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-6-116#Sec23).

In short, H (entropy) and TH can help characterize the stationary distribution and differentiate between a fixed point (zero entropy and zero transition entropy) and a cyclic stationary distribution (non-zero entropy and zero transition entropy).

Best regards,
Arnau

**Comment by ulrmu** [comment]
Thank you for your reply!
A follow-up question: If TH alone is available, does the value suffice to discriminate between fixed points or cycles? (Could you explain a bit more how to make use of TH retrieved from the PROFILE pipeline?)

**Comment by ArnauMontagud** [comment]
I think not, you need both. But, in any case, if you are simulating with MaBoSS, you have both values on the probtraj files. 
Let's discuss this online, it may be more convenient.

**Comment by ulrmu** [comment]
Thank you!
